apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fraud-check-engine
  description: API para gestão de limites / Motor de fraude
spec:
  type: service
  lifecycle: production
  owner: group:cartoes-credito
  system: system:card-services
